In [1]:
import os
import cv2
import torch
import numpy as np

In [2]:
label_path = 'potholes\labels'
image_path = 'potholes\images'

def xywhn2xyxy(x, w=416, h=416, padw=0, padh=0):

    y = x.clone() if isinstance(x, torch.Tensor) else np.copy(x)
    y[:, 0] = w * (x[:, 0] - x[:, 2] / 2) + padw  # top left x    y[:, 1] = h * (x[:, 1] - x[:, 3] / 2) + padh  # top left y
    y[:, 2] = w * (x[:, 0] + x[:, 2] / 2) + padw  # bottom right x
    y[:, 3] = h * (x[:, 1] + x[:, 3] / 2) + padh  # bottom right y
    return y

folder = os.path.exists('potholes\\labelsNew')
if not folder:           
	os.makedirs('potholes\\labelsNew') 

folderlist = os.listdir(label_path)
for i in folderlist:
    label_path_new = os.path.join(label_path,i)
    with open(label_path_new, 'r') as f:
        lb = np.array([x.split() for x in f.read().strip().splitlines()], dtype=np.float32)  # labels
        print(lb)
    read_label = label_path_new.replace(".txt", ".jpg")
    read_label_path = read_label.replace(label_path, image_path)
    print(read_label_path,"ddd")
    img = cv2.imread(str(read_label_path))
    h, w = img.shape[:2]
    lb[:, 1:] = xywhn2xyxy(lb[:, 1:], w, h, 0, 0)


    for _, x in enumerate(lb):
        class_label = int(x[0])

        with open('potholes\\labelsNew\\' + i, 'a') as fw:
            fw.write(str(int(x[0])) + ' ' + str(x[5])+' '+str(x[1]) + ' ' + str(x[2]) + ' ' + str(x[3]) + ' ' + str(
                x[4]) + '\n')

[[0.        0.467624  0.518614  0.377056  0.115077  0.783255 ]
 [0.        0.592912  0.406004  0.297511  0.0947404 0.727551 ]]
potholes\images\00c9sdfq.jpg ddd
[[0.       0.446374 0.786623 0.892748 0.379576 0.685144]]
potholes\images\00yf8rxj.jpg ddd
[[0.       0.489305 0.344725 0.38712  0.304266 0.345122]]
potholes\images\01lx7dej.jpg ddd
[[0.       0.447877 0.490501 0.617507 0.615882 0.447922]]
potholes\images\01paoyy0.jpg ddd
[[0.       0.657923 0.737164 0.396486 0.422527 0.557707]]
potholes\images\02oxhx7t.jpg ddd
[[0.       0.567902 0.738677 0.558451 0.360721 0.809195]]
potholes\images\02tbllvk.jpg ddd
[[0.       0.557957 0.323244 0.715239 0.375542 0.735251]]
potholes\images\03ktj7hp.jpg ddd
[[0.        0.0830664 0.74928   0.166133  0.496252  0.452228 ]]
potholes\images\0486wull.jpg ddd
[[0.       0.453702 0.80655  0.41702  0.284922 0.606903]]
potholes\images\04tuacho.jpg ddd
[[0.       0.727739 0.379946 0.544522 0.293772 0.534018]
 [0.       0.644088 0.385992 0.404741 0.298912 0.